name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * *'

jobs:
  tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    strategy:
      fail-fast: true
      matrix:
        php: ['8.1']

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          coverage: xdebug

      - name: Install dependencies
        run:
          composer update

      - name: Composer normalize
        run:
          composer normalize --dry-run --indent-size=4 --indent-style=space

      - name: Coding Standard
        run:
          vendor/bin/php-cs-fixer fix --diff --dry-run --verbose

      # - name: PHPMD
      #   run:
      #     vendor/bin/phpmd src xml phpmd.xml

      - name: PHPStan
        run:
          vendor/bin/phpstan analyse -vvv

      - name: PHPUnit
        env:
          SMTP_ADDRESS: ${{ secrets.SMTP_ADDRESS }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        run: vendor/bin/phpunit --verbose

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p build/logs/
          cp build/coverage/clover.xml build/logs/clover.xml
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=build/logs/clover.xml -v
        if: matrix.php == '8.1'
